# Generated by Django 5.2 on 2025-04-28 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='payment_complete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_created=True)),
                ('amount', models.CharField(max_length=11)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.register')),
            ],
        ),
        migrations.CreateModel(
            name='security_toke',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=11)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.register')),
            ],
        ),
    ]
