# Generated by Django 5.2 on 2025-04-29 05:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_payment_complete_security_toke'),
    ]

    operations = [
        migrations.AlterField(
            model_name='security_toke',
            name='userid',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='delivery.register'),
        ),
        migrations.DeleteModel(
            name='payment_complete',
        ),
    ]
