version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD:root
      MYSQL_DATABASE:onestop2
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  django-app:
    image: django-app
    container_name: django-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - mysql
    environment:
      DATABASE_URL: mysql://root:root@mysql:3306/onestop2
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: root
    volumes:
      - .:/app
    command: python /app/manage.py runserver 0.0.0.0:8000

volumes:
  mysql_data:

